name: Publish to PyPI
on:
  push:
    tags: v*
  pull_request:
    paths:
    - .github/workflows/publish.yml

jobs:
  pypi-publish:
    name: Upload release to PyPI
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/unyt
    permissions:
      id-token: write
    steps:
    - name: Checkout Source
      uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
    - name: Setup Python
      uses: astral-sh/setup-uv@20cfd1bf945f4377ade1205e4dbc17946fc9a30d # v10.0.1
      with:
        python-version: '3.14'
        enable-cache: false
    - name: Build distributions
      run: uv build
    - name: Publish package distributions to PyPI
      if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')
      uses: pypa/gh-action-pypi-publish@ba38be9e461d3875417946c167d0b5f3d385a247 # v1.14.1
